name: PR Test
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main
jobs:
  test:
    if: github.repository == 'alterationx10/opinionated-zio'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "sbt"
      - name: Test Opinions
        run: sbt test

